name: gmaps_by_road_distance_calculator
description: This is a Package to calculate the by-road distance from one point to another in Gmap.
version: 2.0.6
homepage: "https://github.com/abinvs-2019/gmaps_distance_find_package"

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_polyline_points: ^2.1.0

  google_maps_flutter: ^2.7.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
